name: Feature request
description: "Have an idea for a new feature in UltraCosmetics? Suggest it here!"
labels: ["enhancement"]
body:
    -   type: textarea
        attributes:
            label: "Describe the feature"
        validations:
            required: true
    -   type: textarea
        attributes:
            label: "When/how would it be used?"
        validations:
            required: true
    -   type: input
        attributes:
            label: "Are there alternatives?"
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Additional information
