name: UltraCosmetics
version: @VERSION@
author: iSach
load: POSTWORLD
main: be.isach.ultracosmetics.UltraCosmetics
api-version: 1.13
softdepend:
- LibsDisguises
- Vault
- PlaceholderAPI
- PlayerPoints
- WorldGuard
- Essentials
- LuckPerms
commands:
  ultracosmetics:
    aliases: [uc, cosmetics]
    description: Main Command of Ultra Cosmetics
    usage: /ultracosmetics
permissions:
  ultracosmetics.openmenu:
    default: true
  ultracosmetics.receivechest:
    default: true
  ultracosmetics.treasurechests.buykey:
    default: true
  ultracosmetics.bypass.disabledcommands:
    default: op
  ultracosmetics.bypass.cooldown:
    default: false
  ultracosmetics.command.clear:
    default: op
  ultracosmetics.command.toggle:
    default: op
  ultracosmetics.command.toggle.others:
    default: op
  ultracosmetics.command.give:
    default: op
  ultracosmetics.command.give.others:
    default: op
  ultracosmetics.command.treasure:
    default: op
  ultracosmetics.command.gadgets:
    default: op
  ultracosmetics.command.selfview:
    default: op
  ultracosmetics.command.purge:
    default: op
  ultracosmetics.command.treasurenotification:
    default: true
  ultracosmetics.updatenotify:
    default: op
